train:
  _target_: src.datasets.StocksDataset
  data_dir: saved # exactly the same as save_dir in preprocess.yaml
  instance_transforms: ${transforms.instance_transforms.train}
val: 
  _target_: src.datasets.StocksDataset
  data_dir: ${datasets.train.data_dir}
  instance_transforms: ${transforms.instance_transforms.train}