_target_: src.model.BaseDiffModel
target_dim: 300 # exactly the same as num_train_stocks in preprocess.yaml
time_embed_dim: 128
feature_embed_dim: 16
num_steps: 50
is_unconditional: 0
beta_start: 0.0001
beta_end: 0.5
n_samples: 10
device: ${trainer.device}
diff_model_config:
  layers: 4
  channels: 64
  num_steps: ${model.num_steps}
  nheads: 8
  diffusion_embedding_dim: 128
  is_linear: False
